import { contextBridge, ipcRenderer } from 'electron';

const invoke = (channel: string, ...args: any[]) =>
  ipcRenderer.invoke(channel, ...args);

const listen = (channel: string, cb: (...args: any[]) => void) => {
  const sub = (_event: any, ...args: any[]) => cb(...args);
  ipcRenderer.on(channel, sub);
  return () => ipcRenderer.removeListener(channel, sub);
};

contextBridge.exposeInMainWorld('electronAPI', {
  // --- Window ---
  updateContentDimensions: (d: { width: number; height: number }) => invoke('update-content-dimensions', d),
  updateContentDimensionsCentered: (d: { width: number; height: number }) => invoke('update-content-dimensions-centered', d),
  takeScreenshot: () => invoke('take-screenshot'),
  getScreenshots: () => invoke('get-screenshots'),
  deleteScreenshot: (path: string) => invoke('delete-screenshot', path),
  onScreenshotTaken: (cb: (data: { path: string; preview: string }) => void) => listen('screenshot-taken', cb),
  onCaptureAndProcess: (cb: (data: { path: string; preview: string }) => void) => listen('capture-and-process', cb),
  moveWindowLeft: () => invoke('move-window-left'),
  moveWindowRight: () => invoke('move-window-right'),
  moveWindowUp: () => invoke('move-window-up'),
  moveWindowDown: () => invoke('move-window-down'),
  windowMinimize: () => invoke('window-minimize'),
  windowMaximize: () => invoke('window-maximize'),
  windowClose: () => invoke('window-close'),
  windowIsMaximized: () => invoke('window-is-maximized'),
  quitApp: () => invoke('quit-app'),
  toggleWindow: () => invoke('toggle-window'),
  showWindow: (inactive?: boolean) => invoke('show-window', inactive),
  hideWindow: () => invoke('hide-window'),
  showOverlay: () => invoke('show-overlay'),
  hideOverlay: () => invoke('hide-overlay'),
  onWindowMaximizedChanged: (cb: (isMaximized: boolean) => void) => listen('window-maximized-changed', cb),
  onEnsureExpanded: (cb: () => void) => listen('ensure-expanded', cb),
  openExternal: (url: string) => invoke('open-external', url),
  repairTccPermissions: () => invoke('repair-tcc-permissions'),
  setUndetectable: (state: boolean) => invoke('set-undetectable', state),
  getUndetectable: () => invoke('get-undetectable'),
  setOpenAtLogin: (open: boolean) => invoke('set-open-at-login', open),
  getOpenAtLogin: () => invoke('get-open-at-login'),
  setDisguise: (mode: 'terminal' | 'settings' | 'activity' | 'none') => invoke('set-disguise', mode),
  getDisguise: () => invoke('get-disguise'),
  onDisguiseChanged: (cb: (mode: 'terminal' | 'settings' | 'activity' | 'none') => void) => listen('disguise-changed', cb),
  onToggleExpand: (cb: () => void) => listen('toggle-expand', cb),
  setWindowMode: (mode: 'launcher' | 'overlay', inactive?: boolean) => invoke('set-window-mode', mode, inactive),
  onUndetectableChanged: (cb: (state: boolean) => void) => listen('undetectable-changed', cb),
  setOverlayOpacity: (opacity: number) => invoke('set-overlay-opacity', opacity),
  onOverlayOpacityChanged: (cb: (opacity: number) => void) => listen('overlay-opacity-changed', cb),
  platform: process.platform,

  // --- Audio ---
  getRecognitionLanguages: () => invoke('get-recognition-languages'),
  setSttProvider: (provider: 'none' | 'local-parakeet') => invoke('set-stt-provider', provider),
  getSttProvider: () => invoke('get-stt-provider'),
  localParakeetGetConfig: () => invoke('local-parakeet-get-config'),
  localParakeetSetConfig: (cfg: { modelId?: string; language?: string }) => invoke('local-parakeet-set-config', cfg),
  localParakeetDownloadModel: (modelId: string) => invoke('local-parakeet-download-model', modelId),
  onLocalParakeetDownloadStatus: (cb: (data: { modelId: string; message: string }) => void) => listen('local-parakeet-download-status', cb),
  onLocalParakeetDownloadComplete: (cb: (data: { modelId: string }) => void) => listen('local-parakeet-download-complete', cb),
  onLocalParakeetDownloadError: (cb: (data: { modelId: string; error: string }) => void) => listen('local-parakeet-download-error', cb),
  onSttConfigChanged: (cb: (data: { configured: boolean; provider: string }) => void) => listen('stt-config-changed', cb),
  onCredentialsChanged: (cb: () => void) => listen('credentials-changed', cb),
  onNativeAudioTranscript: (cb: (transcript: { speaker: string; text: string; final: boolean }) => void) => listen('native-audio-transcript', cb),
  analyzeTranscript: (transcript: string) => invoke('analyze-transcript', transcript),
  onAudioCaptureActive: (cb: (data: { channel: 'mic' | 'system'; active: boolean }) => void) => listen('audio-capture-active', cb),
  setChannelMuted: (channel: 'mic' | 'system', muted: boolean) => invoke('set-channel-muted', channel, muted),
  getNativeAudioStatus: () => invoke('native-audio-status'),
  getInputDevices: () => invoke('get-input-devices'),
  getOutputDevices: () => invoke('get-output-devices'),
  setRecognitionLanguage: (key: string) => invoke('set-recognition-language', key),
  getSttLanguage: () => invoke('get-stt-language'),
  onSystemAudioPermissionDenied: (cb: (message: string) => void) => listen('system-audio-permission-denied', cb),
  getSystemAudioPermissionWarning: () => invoke('get-system-audio-permission-warning'),
  onDeviceSelectionApplied: (cb: (payload: { kind: 'input' | 'output'; requested: string | null; actual: string | null; fellBack: boolean; reason?: string }) => void) => listen('device-selection-applied', cb),
  onAudioCaptureFailed: (cb: (payload: { channel: 'system' | 'mic'; message: string; attempt: number; maxAttempts: number; terminal?: boolean; stuck?: boolean }) => void) => listen('audio-capture-failed', cb),
  onAudioInputAutoSwitched: (cb: (payload: { from: string; to: string; reason: string; message?: string }) => void) => listen('audio-input-auto-switched', cb),
  onSttStatusChanged: (cb: (data: { state: 'connected' | 'reconnecting' | 'failed' | 'awaiting-audio'; provider: string; error?: string; channel: 'user' | 'interviewer'; reconnectAttempts?: number }) => void) => listen('stt-status', cb),
  startAudioTest: (deviceId?: string) => invoke('start-audio-test', deviceId),
  stopAudioTest: () => invoke('stop-audio-test'),
  onAudioTestLevel: (cb: (level: number) => void) => listen('audio-test-level', cb),
  onAudioTestSystemLevel: (cb: (level: number) => void) => listen('audio-test-system-level', cb),
  onAudioTestSystemError: (cb: (errorMessage: string) => void) => listen('audio-test-system-error', cb),

  // --- Provider ---
  getCurrentLlmConfig: () => invoke('get-current-llm-config'),
  testLlmConnection: (provider: 'gemini' | 'groq' | 'openai' | 'claude' | 'deepseek', apiKey: string) => invoke('test-llm-connection', provider, apiKey),
  setApiKey: (provider: 'gemini' | 'groq' | 'openai' | 'claude' | 'deepseek', apiKey: string) => invoke('set-api-key', provider, apiKey),
  getStoredCredentials: () => invoke('get-stored-credentials'),
  getDefaultModel: () => invoke('get-default-model'),
  setModel: (modelId: string) => invoke('set-model', modelId),
  toggleModelSelector: (coords: { x: number; y: number; activate?: boolean }) => invoke('toggle-model-selector', coords),
  modelSelectorCloseIfOpen: () => invoke('model-selector:close-if-open'),
  onModelChanged: (cb: (modelId: string) => void) => listen('model-changed', cb),
  setProviderPreferredModel: (provider: 'gemini' | 'groq' | 'openai' | 'claude' | 'deepseek', modelId: string) => invoke('set-provider-preferred-model', provider, modelId),

  // --- Meeting ---
  getMeetingActive: () => invoke('get-meeting-active'),
  onMeetingStateChanged: (cb: (data: { isActive: boolean }) => void) => listen('meeting-state-changed', cb),
  getIntelligenceContext: () => invoke('get-intelligence-context'),
  resetIntelligence: () => invoke('reset-intelligence'),
  startMeeting: (metadata?: any) => invoke('start-meeting', metadata),
  endMeeting: () => invoke('end-meeting'),
  abortMeeting: () => invoke('abort-meeting'),
  getRecentMeetings: () => invoke('get-recent-meetings'),
  getMeetingDetails: (id: string) => invoke('get-meeting-details', id),
  updateMeetingTitle: (id: string, title: string) => invoke('update-meeting-title', { id, title }),
  updateMeetingSummary: (id: string, updates: any) => invoke('update-meeting-summary', { id, updates }),
  deleteMeeting: (id: string) => invoke('delete-meeting', id),
  retryMeetingSummary: (id: string) => invoke('retry-meeting-summary', id),
  onMeetingsUpdated: (cb: () => void) => listen('meetings-updated', cb),
  onSessionReset: (cb: () => void) => listen('session-reset', cb),
  onDialogueDrained: (cb: (turns: Array<{ speaker: 'Me' | 'Them'; text: string; final: boolean }>) => void) => listen('dialogue-drained', cb),
  chatStreamStart: (streamId: string, messages: unknown[], opts?: { system?: string }) =>
    invoke('chat:stream', { streamId, messages, ...opts }) as Promise<{ success: boolean; error?: string }>,
  chatStreamAbort: (streamId: string) => { ipcRenderer.send('chat:stream-abort', streamId); },
  onChatStreamEvent: (cb: (evt: { streamId: string; type: 'chunk' | 'end' | 'error'; chunk?: unknown; error?: string }) => void) => listen('chat:stream-event', cb),

  // --- Settings ---
  openSettingsTab: (tab: string) => invoke('settings:open-tab', tab),
  onOpenSettingsTab: (cb: (tab: string) => void) => listen('settings:open-tab', cb),
  onSettingsVisibilityChange: (cb: (isVisible: boolean) => void) => listen('settings-visibility-changed', cb),
  toggleSettingsWindow: (coords?: { x: number; y: number }) => invoke('toggle-settings-window', coords),
  closeSettingsWindow: () => invoke('close-settings-window'),
  getKeybinds: () => invoke('keybinds:get-all'),
  setKeybind: (id: string, accelerator: string) => invoke('keybinds:set', id, accelerator),
  resetKeybinds: () => invoke('keybinds:reset'),
  onKeybindsUpdate: (cb: (keybinds: Array<any>) => void) => listen('keybinds:update', cb),
  onKeybindRegistrationFailed: (cb: (data: { id: string; accelerator: string }) => void) => listen('keybinds:registration-failed', cb),
  onGlobalShortcut: (cb: (data: { action: string }) => void) => listen('global-shortcut', cb),
  stealthTapAvailable: () => invoke('stealth-tap:available'),
  stealthTapOpenSettings: () => invoke('stealth-tap:open-settings'),
  stealthTapStop: () => invoke('stealth-tap:stop'),
  stealthTapStart: () => invoke('stealth-tap:start'),
  onStealthTapState: (cb: (state: { active: boolean; reason?: string }) => void) => listen('stealth-tap-state', cb),
  onStealthKeyCaptured: (cb: (ev: { keyCode: number; chars: string; flags: number; isKeyDown: boolean }) => void) => listen('stealth-key-captured', cb),
  contextGetDescription: () => invoke('context:get-description'),
  contextSaveDescription: (content: string) => invoke('context:save-description', content),
  contextGetFiles: () => invoke('context:get-files'),
  contextUploadFile: () => invoke('context:upload-file'),
  contextDeleteFile: (id: string) => invoke('context:delete-file', id),
  getVerboseLogging: () => invoke('get-verbose-logging'),
  setVerboseLogging: (enabled: boolean) => invoke('set-verbose-logging', enabled),
  getQuestionAnalysisConfig: () => invoke('get-question-analysis-config'),
  setQuestionAnalysisConfig: (config: { enabled?: boolean; interval?: number; model?: string; openRouterApiKey?: string; window?: number }) => invoke('set-question-analysis-config', config),
  onQuestionAnalysisConfigChanged: (cb: (config: { enabled: boolean; interval: number }) => void) => listen('question-analysis-config-changed', cb),
  getLogFilePath: () => invoke('get-log-file-path'),
  openLogFile: () => invoke('open-log-file'),
  getArch: () => invoke('get-arch'),
  getOsVersion: () => invoke('get-os-version'),

  // --- Skills ---
  skillsList: () => invoke('skills:list'),
  skillsGet: (name: string) => invoke('skills:get', name),
  skillsImport: () => invoke('skills:import'),
  skillsToggle: (name: string, enabled: boolean) => invoke('skills:toggle', name, enabled),
  skillsUpdate: (name: string, patch: { enabled?: boolean; content?: string; description?: string }) => invoke('skills:update', name, patch),
  skillsRemove: (name: string) => invoke('skills:remove', name),
  onSkillsChanged: (cb: () => void) => listen('skills:changed', cb),

  // --- Server ---
  checkPermissions: () => invoke('permissions:check'),
  flushDatabase: () => invoke('flush-database'),

});
